/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ConfirmDialog: typeof import('./src/components/ConfirmDialog.vue')['default']
    DownloadConfirmDialog: typeof import('./src/components/DownloadConfirmDialog.vue')['default']
    FarmDuplicateDialog: typeof import('./src/components/FarmDuplicateDialog.vue')['default']
    FeatureEditDialog: typeof import('./src/components/FeatureEditDialog.vue')['default']
    FileUploadPopup: typeof import('./src/components/FileUploadPopup.vue')['default']
    GeoJsonExportDialog: typeof import('./src/components/GeoJsonExportDialog.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    Map: typeof import('./src/components/Map.vue')['default']
    ShapefileImportDialog: typeof import('./src/components/ShapefileImportDialog.vue')['default']
    Toolbox: typeof import('./src/components/Toolbox.vue')['default']
  }
}
